name: adb-assistant
options:
  bundleIdPrefix: com.aorobator
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  ADBAssistant:
    type: framework
    platform: macOS
    sources:
      - path: Sources/ADBAssistant
    resources:
      - path: Resources/FrameworkInfo.plist
        destination: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aorobator.ADBAssistant
        SWIFT_STRICT_CONCURRENCY: complete
        INFOPLIST_FILE: Resources/FrameworkInfo.plist
    
  adb-assistant:
    type: application
    platform: macOS
    sources:
      - path: Sources/App
    dependencies:
      - target: ADBAssistant
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aorobator.adb-assistant
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    
  ADBAssistantTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ADBAssistantTests
    dependencies:
      - target: ADBAssistant
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.aorobator.ADBAssistantTests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/adb-assistant.app/Contents/MacOS/adb-assistant
        BUNDLE_LOADER: $(TEST_HOST)

schemes:
  adb-assistant:
    build:
      targets:
        adb-assistant: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ADBAssistantTests
      gatherCoverageData: true
